import { GraveStoneOrder, } from './types'
import { Font } from './store'

const base = 'https://behavior-dev-01.com'

export interface Product {
  [k: string]: any
  id: number
  name: string
  image: string
}

export async function fetchProductsByCategory(category:number):Promise<Product[]> {

  // fixtures
  if (category === -1) {
    return [
      <Product>{
        name: Font[Font.Helvetica],
        image: '/images/font-helvetica.jpg',
      },<Product>{
        name: Font[Font.Antikva],
        image: '/images/font-antikva.jpg',
      }, <Product>{
        name: Font[Font.Skriveskrift],
        image: '/images/font-antikva.jpg',
      },<Product>{
        name: Font[Font.Bronze],
        image: '/images/font-antikva.jpg',
      },
    ]
  }
  if (category === -2) {
    return [
        <Product>{
        name: 'Multicolor Poleret urnesten',
        image:'/images/Multicolor-Poleret-urnesten.jpg',
      },<Product>{
        name: 'Multicolor 50x50',
        image:'/images/Multicolor-50.jpg',
      }
    ]
  }
  if (category === -3) {
    return [
      <Product>{name: `Tak for alt`,},
      <Product>{name: `Altid frejdig når du går`,},
      <Product>{name: `Hvil i fred`,},
      <Product>{name: `Elsket og savnet`,},
      <Product>{name: `Altid i vore hjerter`,},
      <Product>{name: `Gemt i vore hjerter`,},
      <Product>{name: `Minderne lever`,},
      <Product>{name: `Et sidste farvel`,},
      <Product>{name: `Mindes med kærlighed`,},
      <Product>{name: `Tak for gode minder`,},
    ]
  }

  // actual data
  const json = await _fetchRemoteWc()
  const products:Product[] = json
    .filter(f => f.categories.find((cat:any) => cat.id === category))
    .map (f => Object.freeze({
        ...f,
        get image () {return f.images[0] ? f.images[0].src : 'http://0.0.0.0/missing-img'},
      })
    )

  return products
}

export async function sendToBasket(order:GraveStoneOrder) {
  // map Order to woo commerce basket item
  const woo = [
    // {id: 15}
    //   {
    //     action: 'woocommerce_ajax_add_to_cart',
    //     product_id: product_id,
    //     product_sku: '',
    //     quantity: product_qty,
    //     variation_id: variation_id,
    //   }
  ]

  // send all off

  // redirecto to woocommerce basket
}

// const categoryMap:Readonly<{[k: number]: StoneBase['graveCategory']}> = {
//   18: 'plænesten',
//   19: 'urnesten',
// }
export enum CategoryID {
  Eftertekst = 46,
  Plænesten = 19,
  Urnesten = 47,
  Skrifttype = 48,
}

export async function _fetchRemoteWc ():Promise<any[]> {
  const ck = 'ck_0b02b9744e2ae7d327bd28b50ad5d966ea97c7b8'
  const cs = 'cs_9f5f34346fc2daf5b16bb96fc30870903c3b07c8'
  const url = `${base}/wp-json/wc/v3/products?consumer_key=${ck}&consumer_secret=${cs}&per_page=100`

  if (sessionStorage[url]) {
    try {
      const revived = JSON.parse(sessionStorage[url])
      if (Array.isArray(revived) && revived.length > 0) {
        console.debug(`Returning ${revived.length} items from cache`)
        return revived
      }
    }
    catch (e) {
      console.log('cache was corrupt')
      delete sessionStorage[url]
    }
  }

  if (sessionStorage.dev) {
    const _fixture = fix()
    return _fixture
  }

  const res = await fetch(url)
  const txt = await res.json()

  if (!sessionStorage[url]) {
    sessionStorage[url] = JSON.stringify(txt)
  }
  return txt
}

export async function fetchBasketProductsHack () {
  const res = await fetch(`${base}/basket`)
  const html = await res.text()

  const fragment = document.createElement('div')
  fragment.innerHTML = html

  const products:string[] = [
      ...fragment.querySelectorAll('.remove[data-product_id]') as any,
    ]
    .map(aEl => aEl.getAttribute('data-product_id'))

  return products
}



function fix() {
  return [
    {
      'id': 182,
      'name': 'Tak for alt',
      'slug': 'tak-for-alt',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/tak-for-alt\/',
      'date_created': '2019-03-18T14:20:40',
      'date_created_gmt': '2019-03-18T14:20:40',
      'date_modified': '2019-03-18T14:20:40',
      'date_modified_gmt': '2019-03-18T14:20:40',
      'type': 'simple',
      'status': 'publish',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': '',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 32, 'name': 'Eftertekst', 'slug': 'eftertekst'}],
      'tags': [],
      'images': [],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 1807, 'key': '_wpas_done_all', 'value': '1'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/182'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 181,
      'name': 'Eftertekst:Hvil i fred',
      'slug': 'efterteksthvil-i-fred',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/efterteksthvil-i-fred\/',
      'date_created': '2019-03-18T14:19:47',
      'date_created_gmt': '2019-03-18T14:19:47',
      'date_modified': '2019-03-18T14:19:47',
      'date_modified_gmt': '2019-03-18T14:19:47',
      'type': 'simple',
      'status': 'publish',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': '',
      'price': '999',
      'regular_price': '999',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '<span class="woocommerce-Price-amount amount">999.00<span class="woocommerce-Price-currencySymbol">DKK<\/span><\/span>',
      'on_sale': false,
      'purchasable': true,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [144, 179],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}],
      'tags': [],
      'images': [],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 1771, 'key': '_wpas_done_all', 'value': '1'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/181'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 179,
      'name': 'Hjerte gravsten, Multicolour granit',
      'slug': 'hjerte-gravsten-multicolour-granit',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/hjerte-gravsten-multicolour-granit\/',
      'date_created': '2019-03-18T14:10:35',
      'date_created_gmt': '2019-03-18T14:10:35',
      'date_modified': '2019-03-18T14:10:35',
      'date_modified_gmt': '2019-03-18T14:10:35',
      'type': 'simple',
      'status': 'publish',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': '',
      'price': '9999',
      'regular_price': '9999',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '<span class="woocommerce-Price-amount amount">9,999.00<span class="woocommerce-Price-currencySymbol">DKK<\/span><\/span>',
      'on_sale': false,
      'purchasable': true,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [144, 181],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}],
      'tags': [],
      'images': [{
        'id': 180,
        'date_created': '2019-03-18T14:09:54',
        'date_created_gmt': '2019-03-18T14:09:54',
        'date_modified': '2019-03-18T14:09:54',
        'date_modified_gmt': '2019-03-18T14:09:54',
        'src': 'https:\/\/www.victorfenger.dk\/wp-content\/uploads\/2019\/03\/Multicolor-hjerte.jpg',
        'name': 'Multicolor-hjerte',
        'alt': ''
      }],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 1734, 'key': '_wpas_done_all', 'value': '1'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/179'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 166,
      'name': 'Import placeholder for 90',
      'slug': 'import-placeholder-for-90',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/import-placeholder-for-90\/',
      'date_created': '2019-03-11T13:48:58',
      'date_created_gmt': '2019-03-11T13:48:58',
      'date_modified': '2019-03-11T13:48:58',
      'date_modified_gmt': '2019-03-11T13:48:58',
      'type': 'simple',
      'status': 'importing',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': 'woo-hoodie-blue-logo',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [144, 181, 179],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}],
      'tags': [],
      'images': [],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 1619, 'key': '_original_id', 'value': '90'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/166'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 165,
      'name': 'Import placeholder for 89',
      'slug': 'import-placeholder-for-89',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/import-placeholder-for-89\/',
      'date_created': '2019-03-11T13:48:58',
      'date_created_gmt': '2019-03-11T13:48:58',
      'date_modified': '2019-03-11T13:48:58',
      'date_modified_gmt': '2019-03-11T13:48:58',
      'type': 'simple',
      'status': 'importing',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': 'wp-pennant',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [181, 144, 179],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}],
      'tags': [],
      'images': [],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 1584, 'key': '_original_id', 'value': '89'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/165'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 164,
      'name': 'Import placeholder for 87',
      'slug': 'import-placeholder-for-87',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/import-placeholder-for-87\/',
      'date_created': '2019-03-11T13:48:58',
      'date_created_gmt': '2019-03-11T13:48:58',
      'date_modified': '2019-03-11T13:48:58',
      'date_modified_gmt': '2019-03-11T13:48:58',
      'type': 'simple',
      'status': 'importing',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': 'logo-collection',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [144, 179, 181],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}],
      'tags': [],
      'images': [],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 1549, 'key': '_original_id', 'value': '87'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/164'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 163,
      'name': 'Import placeholder for 85',
      'slug': 'import-placeholder-for-85',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/import-placeholder-for-85\/',
      'date_created': '2019-03-11T13:48:58',
      'date_created_gmt': '2019-03-11T13:48:58',
      'date_modified': '2019-03-11T13:48:58',
      'date_modified_gmt': '2019-03-11T13:48:58',
      'type': 'simple',
      'status': 'importing',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': 'Woo-beanie-logo',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [179, 144, 181],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}],
      'tags': [],
      'images': [],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 1514, 'key': '_original_id', 'value': '85'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/163'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 162,
      'name': 'Import placeholder for 83',
      'slug': 'import-placeholder-for-83',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/import-placeholder-for-83\/',
      'date_created': '2019-03-11T13:48:58',
      'date_created_gmt': '2019-03-11T13:48:58',
      'date_modified': '2019-03-11T13:48:58',
      'date_modified_gmt': '2019-03-11T13:48:58',
      'type': 'simple',
      'status': 'importing',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': 'Woo-tshirt-logo',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [144, 181, 179],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}],
      'tags': [],
      'images': [],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 1479, 'key': '_original_id', 'value': '83'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/162'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 161,
      'name': 'Import placeholder for 81',
      'slug': 'import-placeholder-for-81',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/import-placeholder-for-81\/',
      'date_created': '2019-03-11T13:48:57',
      'date_created_gmt': '2019-03-11T13:48:57',
      'date_modified': '2019-03-11T13:48:57',
      'date_modified_gmt': '2019-03-11T13:48:57',
      'type': 'simple',
      'status': 'importing',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': 'woo-hoodie-blue',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [179, 181, 144],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}],
      'tags': [],
      'images': [],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 1444, 'key': '_original_id', 'value': '81'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/161'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 160,
      'name': 'Import placeholder for 80',
      'slug': 'import-placeholder-for-80',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/import-placeholder-for-80\/',
      'date_created': '2019-03-11T13:48:57',
      'date_created_gmt': '2019-03-11T13:48:57',
      'date_modified': '2019-03-11T13:48:57',
      'date_modified_gmt': '2019-03-11T13:48:57',
      'type': 'simple',
      'status': 'importing',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': 'woo-hoodie-green',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [181, 179, 144],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}],
      'tags': [],
      'images': [],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 1409, 'key': '_original_id', 'value': '80'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/160'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 159,
      'name': 'Import placeholder for 79',
      'slug': 'import-placeholder-for-79',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/import-placeholder-for-79\/',
      'date_created': '2019-03-11T13:48:57',
      'date_created_gmt': '2019-03-11T13:48:57',
      'date_modified': '2019-03-11T13:48:57',
      'date_modified_gmt': '2019-03-11T13:48:57',
      'type': 'simple',
      'status': 'importing',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': 'woo-hoodie-red',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [179, 144, 181],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}],
      'tags': [],
      'images': [],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 1374, 'key': '_original_id', 'value': '79'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/159'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 158,
      'name': 'Import placeholder for 78',
      'slug': 'import-placeholder-for-78',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/import-placeholder-for-78\/',
      'date_created': '2019-03-11T13:48:57',
      'date_created_gmt': '2019-03-11T13:48:57',
      'date_modified': '2019-03-11T13:48:57',
      'date_modified_gmt': '2019-03-11T13:48:57',
      'type': 'simple',
      'status': 'importing',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': 'woo-vneck-tee-blue',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [144, 179, 181],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}],
      'tags': [],
      'images': [],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 1339, 'key': '_original_id', 'value': '78'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/158'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 157,
      'name': 'Import placeholder for 77',
      'slug': 'import-placeholder-for-77',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/import-placeholder-for-77\/',
      'date_created': '2019-03-11T13:48:57',
      'date_created_gmt': '2019-03-11T13:48:57',
      'date_modified': '2019-03-11T13:48:57',
      'date_modified_gmt': '2019-03-11T13:48:57',
      'type': 'simple',
      'status': 'importing',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': 'woo-vneck-tee-green',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [144, 181, 179],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}],
      'tags': [],
      'images': [],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 1304, 'key': '_original_id', 'value': '77'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/157'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 156,
      'name': 'Import placeholder for 76',
      'slug': 'import-placeholder-for-76',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/import-placeholder-for-76\/',
      'date_created': '2019-03-11T13:48:57',
      'date_created_gmt': '2019-03-11T13:48:57',
      'date_modified': '2019-03-11T13:48:57',
      'date_modified_gmt': '2019-03-11T13:48:57',
      'type': 'simple',
      'status': 'importing',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': 'woo-vneck-tee-red',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [179, 144, 181],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}],
      'tags': [],
      'images': [],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 1269, 'key': '_original_id', 'value': '76'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/156'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 155,
      'name': 'Import placeholder for 75',
      'slug': 'import-placeholder-for-75',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/import-placeholder-for-75\/',
      'date_created': '2019-03-11T13:48:56',
      'date_created_gmt': '2019-03-11T13:48:56',
      'date_modified': '2019-03-11T13:48:56',
      'date_modified_gmt': '2019-03-11T13:48:56',
      'type': 'simple',
      'status': 'importing',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': 'woo-single',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [179, 144, 181],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}],
      'tags': [],
      'images': [],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 1234, 'key': '_original_id', 'value': '75'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/155'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 154,
      'name': 'Import placeholder for 73',
      'slug': 'import-placeholder-for-73',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/import-placeholder-for-73\/',
      'date_created': '2019-03-11T13:48:56',
      'date_created_gmt': '2019-03-11T13:48:56',
      'date_modified': '2019-03-11T13:48:56',
      'date_modified_gmt': '2019-03-11T13:48:56',
      'type': 'simple',
      'status': 'importing',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': 'woo-album',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [179, 181, 144],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}],
      'tags': [],
      'images': [],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 1199, 'key': '_original_id', 'value': '73'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/154'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 153,
      'name': 'Import placeholder for 70',
      'slug': 'import-placeholder-for-70',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/import-placeholder-for-70\/',
      'date_created': '2019-03-11T13:48:56',
      'date_created_gmt': '2019-03-11T13:48:56',
      'date_modified': '2019-03-11T13:48:56',
      'date_modified_gmt': '2019-03-11T13:48:56',
      'type': 'simple',
      'status': 'importing',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': 'woo-polo',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [144, 181, 179],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}],
      'tags': [],
      'images': [],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 1164, 'key': '_original_id', 'value': '70'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/153'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 152,
      'name': 'Import placeholder for 68',
      'slug': 'import-placeholder-for-68',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/import-placeholder-for-68\/',
      'date_created': '2019-03-11T13:48:56',
      'date_created_gmt': '2019-03-11T13:48:56',
      'date_modified': '2019-03-11T13:48:56',
      'date_modified_gmt': '2019-03-11T13:48:56',
      'type': 'simple',
      'status': 'importing',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': 'woo-long-sleeve-tee',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [179, 181, 144],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}],
      'tags': [],
      'images': [],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 1129, 'key': '_original_id', 'value': '68'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/152'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 151,
      'name': 'Import placeholder for 66',
      'slug': 'import-placeholder-for-66',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/import-placeholder-for-66\/',
      'date_created': '2019-03-11T13:48:55',
      'date_created_gmt': '2019-03-11T13:48:55',
      'date_modified': '2019-03-11T13:48:55',
      'date_modified_gmt': '2019-03-11T13:48:55',
      'type': 'simple',
      'status': 'importing',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': 'woo-hoodie-with-zipper',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [179, 181, 144],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}],
      'tags': [],
      'images': [],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 1094, 'key': '_original_id', 'value': '66'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/151'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 150,
      'name': 'Import placeholder for 64',
      'slug': 'import-placeholder-for-64',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/import-placeholder-for-64\/',
      'date_created': '2019-03-11T13:48:55',
      'date_created_gmt': '2019-03-11T13:48:55',
      'date_modified': '2019-03-11T13:48:55',
      'date_modified_gmt': '2019-03-11T13:48:55',
      'type': 'simple',
      'status': 'importing',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': 'woo-hoodie-with-pocket',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [144, 181, 179],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}],
      'tags': [],
      'images': [],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 1059, 'key': '_original_id', 'value': '64'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/150'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 149,
      'name': 'Import placeholder for 62',
      'slug': 'import-placeholder-for-62',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/import-placeholder-for-62\/',
      'date_created': '2019-03-11T13:48:55',
      'date_created_gmt': '2019-03-11T13:48:55',
      'date_modified': '2019-03-11T13:48:55',
      'date_modified_gmt': '2019-03-11T13:48:55',
      'type': 'simple',
      'status': 'importing',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': 'woo-sunglasses',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [179, 144, 181],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}],
      'tags': [],
      'images': [],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 1024, 'key': '_original_id', 'value': '62'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/149'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 148,
      'name': 'Import placeholder for 60',
      'slug': 'import-placeholder-for-60',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/import-placeholder-for-60\/',
      'date_created': '2019-03-11T13:48:55',
      'date_created_gmt': '2019-03-11T13:48:55',
      'date_modified': '2019-03-11T13:48:55',
      'date_modified_gmt': '2019-03-11T13:48:55',
      'type': 'simple',
      'status': 'importing',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '',
      'short_description': '',
      'sku': 'woo-cap',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': -1,
      'download_expiry': -1,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [179, 181, 144],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}],
      'tags': [],
      'images': [],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 989, 'key': '_original_id', 'value': '60'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/148'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 147,
      'name': 'Belt',
      'slug': 'belt',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/belt\/',
      'date_created': '2019-03-11T13:48:55',
      'date_created_gmt': '2019-03-11T13:48:55',
      'date_modified': '2019-03-11T13:49:17',
      'date_modified_gmt': '2019-03-11T13:49:17',
      'type': 'simple',
      'status': 'publish',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.<\/p>\n',
      'short_description': '<p>This is a simple product.<\/p>\n',
      'sku': 'woo-belt',
      'price': '55',
      'regular_price': '65',
      'sale_price': '55',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '<del><span class="woocommerce-Price-amount amount">65.00<span class="woocommerce-Price-currencySymbol">DKK<\/span><\/span><\/del> <ins><span class="woocommerce-Price-amount amount">55.00<span class="woocommerce-Price-currencySymbol">DKK<\/span><\/span><\/ins>',
      'on_sale': true,
      'purchasable': true,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': 0,
      'download_expiry': 0,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [146],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 22, 'name': 'Accessories', 'slug': 'accessories'}],
      'tags': [],
      'images': [{
        'id': 176,
        'date_created': '2019-03-11T13:49:17',
        'date_created_gmt': '2019-03-11T13:49:17',
        'date_modified': '2019-03-11T13:49:17',
        'date_modified_gmt': '2019-03-11T13:49:17',
        'src': 'https:\/\/www.victorfenger.dk\/wp-content\/uploads\/2019\/03\/belt-2.jpg',
        'name': 'belt-2.jpg',
        'alt': ''
      }],
      'attributes': [],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 954, 'key': '_original_id', 'value': '58'}, {
        'id': 1675,
        'key': '_wpcom_is_markdown',
        'value': '1'
      }, {'id': 1678, 'key': '_wpas_done_all', 'value': '1'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/147'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 146,
      'name': 'Beanie',
      'slug': 'beanie',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/beanie\/',
      'date_created': '2019-03-11T13:48:54',
      'date_created_gmt': '2019-03-11T13:48:54',
      'date_modified': '2019-03-11T13:49:15',
      'date_modified_gmt': '2019-03-11T13:49:15',
      'type': 'simple',
      'status': 'publish',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.<\/p>\n',
      'short_description': '<p>This is a simple product.<\/p>\n',
      'sku': 'woo-beanie',
      'price': '18',
      'regular_price': '20',
      'sale_price': '18',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '<del><span class="woocommerce-Price-amount amount">20.00<span class="woocommerce-Price-currencySymbol">DKK<\/span><\/span><\/del> <ins><span class="woocommerce-Price-amount amount">18.00<span class="woocommerce-Price-currencySymbol">DKK<\/span><\/span><\/ins>',
      'on_sale': true,
      'purchasable': true,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': 0,
      'download_expiry': 0,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [147],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 22, 'name': 'Accessories', 'slug': 'accessories'}],
      'tags': [],
      'images': [{
        'id': 175,
        'date_created': '2019-03-11T13:49:14',
        'date_created_gmt': '2019-03-11T13:49:14',
        'date_modified': '2019-03-11T13:49:14',
        'date_modified_gmt': '2019-03-11T13:49:14',
        'src': 'https:\/\/www.victorfenger.dk\/wp-content\/uploads\/2019\/03\/beanie-2.jpg',
        'name': 'beanie-2.jpg',
        'alt': ''
      }],
      'attributes': [{
        'id': 1,
        'name': 'Color',
        'position': 0,
        'visible': true,
        'variation': false,
        'options': ['Red']
      }],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 919, 'key': '_original_id', 'value': '48'}, {
        'id': 1667,
        'key': '_wpcom_is_markdown',
        'value': '1'
      }, {'id': 1670, 'key': '_wpas_done_all', 'value': '1'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/146'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 145,
      'name': 'T-Shirt',
      'slug': 't-shirt',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/t-shirt\/',
      'date_created': '2019-03-11T13:48:54',
      'date_created_gmt': '2019-03-11T13:48:54',
      'date_modified': '2019-03-11T13:49:13',
      'date_modified_gmt': '2019-03-11T13:49:13',
      'type': 'simple',
      'status': 'publish',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.<\/p>\n',
      'short_description': '<p>This is a simple product.<\/p>\n',
      'sku': 'woo-tshirt',
      'price': '18',
      'regular_price': '18',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '<span class="woocommerce-Price-amount amount">18.00<span class="woocommerce-Price-currencySymbol">DKK<\/span><\/span>',
      'on_sale': false,
      'purchasable': true,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': 0,
      'download_expiry': 0,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [142],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 20, 'name': 'Tshirts', 'slug': 'tshirts'}],
      'tags': [],
      'images': [{
        'id': 174,
        'date_created': '2019-03-11T13:49:12',
        'date_created_gmt': '2019-03-11T13:49:12',
        'date_modified': '2019-03-11T13:49:12',
        'date_modified_gmt': '2019-03-11T13:49:12',
        'src': 'https:\/\/www.victorfenger.dk\/wp-content\/uploads\/2019\/03\/tshirt-2.jpg',
        'name': 'tshirt-2.jpg',
        'alt': ''
      }],
      'attributes': [{
        'id': 1,
        'name': 'Color',
        'position': 0,
        'visible': true,
        'variation': false,
        'options': ['Gray']
      }],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 884, 'key': '_original_id', 'value': '47'}, {
        'id': 1659,
        'key': '_wpcom_is_markdown',
        'value': '1'
      }, {'id': 1662, 'key': '_wpas_done_all', 'value': '1'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/145'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 144,
      'name': 'Hoodie with Logo',
      'slug': 'hoodie-with-logo',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/hoodie-with-logo\/',
      'date_created': '2019-03-11T13:48:54',
      'date_created_gmt': '2019-03-11T13:48:54',
      'date_modified': '2019-03-11T17:36:18',
      'date_modified_gmt': '2019-03-11T17:36:18',
      'type': 'simple',
      'status': 'publish',
      'featured': true,
      'catalog_visibility': 'visible',
      'description': '<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.<\/p>\n',
      'short_description': '<p>This is a simple product. 123321<\/p>\n',
      'sku': 'woo-hoodie-with-logo',
      'price': '42.00',
      'regular_price': '42.00',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '<span class="woocommerce-Price-amount amount">42.00<span class="woocommerce-Price-currencySymbol">DKK<\/span><\/span>',
      'on_sale': false,
      'purchasable': true,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': 0,
      'download_expiry': 0,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'instock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [143, 181, 179],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 18, 'name': 'Uncategorised', 'slug': 'uncategorised'}, {
        'id': 21,
        'name': 'Hoodies',
        'slug': 'hoodies'
      }],
      'tags': [],
      'images': [{
        'id': 173,
        'date_created': '2019-03-11T13:49:10',
        'date_created_gmt': '2019-03-11T13:49:10',
        'date_modified': '2019-03-11T13:49:10',
        'date_modified_gmt': '2019-03-11T13:49:10',
        'src': 'https:\/\/www.victorfenger.dk\/wp-content\/uploads\/2019\/03\/hoodie-with-logo-2.jpg',
        'name': 'hoodie-with-logo-2.jpg',
        'alt': ''
      }],
      'attributes': [{
        'id': 1,
        'name': 'Color',
        'position': 0,
        'visible': true,
        'variation': false,
        'options': ['Blue']
      }],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 849, 'key': '_original_id', 'value': '46'}, {
        'id': 1651,
        'key': '_wpcom_is_markdown',
        'value': '1'
      }, {'id': 1654, 'key': '_wpas_done_all', 'value': '1'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/144'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 143,
      'name': 'Hoodie',
      'slug': 'hoodie',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/hoodie\/',
      'date_created': '2019-03-11T13:48:54',
      'date_created_gmt': '2019-03-11T13:48:54',
      'date_modified': '2019-03-11T13:49:10',
      'date_modified_gmt': '2019-03-11T13:49:10',
      'type': 'variable',
      'status': 'publish',
      'featured': false,
      'catalog_visibility': 'visible',
      'description': '<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.<\/p>\n',
      'short_description': '<p>This is a variable product.<\/p>\n',
      'sku': 'woo-hoodie',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': 0,
      'download_expiry': 0,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'outofstock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [144],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 21, 'name': 'Hoodies', 'slug': 'hoodies'}],
      'tags': [],
      'images': [{
        'id': 170,
        'date_created': '2019-03-11T13:49:05',
        'date_created_gmt': '2019-03-11T13:49:05',
        'date_modified': '2019-03-11T13:49:05',
        'date_modified_gmt': '2019-03-11T13:49:05',
        'src': 'https:\/\/www.victorfenger.dk\/wp-content\/uploads\/2019\/03\/hoodie-2.jpg',
        'name': 'hoodie-2.jpg',
        'alt': ''
      }, {
        'id': 171,
        'date_created': '2019-03-11T13:49:07',
        'date_created_gmt': '2019-03-11T13:49:07',
        'date_modified': '2019-03-11T13:49:07',
        'date_modified_gmt': '2019-03-11T13:49:07',
        'src': 'https:\/\/www.victorfenger.dk\/wp-content\/uploads\/2019\/03\/hoodie-blue-1.jpg',
        'name': 'hoodie-blue-1.jpg',
        'alt': ''
      }, {
        'id': 172,
        'date_created': '2019-03-11T13:49:08',
        'date_created_gmt': '2019-03-11T13:49:08',
        'date_modified': '2019-03-11T13:49:08',
        'date_modified_gmt': '2019-03-11T13:49:08',
        'src': 'https:\/\/www.victorfenger.dk\/wp-content\/uploads\/2019\/03\/hoodie-green-1.jpg',
        'name': 'hoodie-green-1.jpg',
        'alt': ''
      }, {
        'id': 173,
        'date_created': '2019-03-11T13:49:10',
        'date_created_gmt': '2019-03-11T13:49:10',
        'date_modified': '2019-03-11T13:49:10',
        'date_modified_gmt': '2019-03-11T13:49:10',
        'src': 'https:\/\/www.victorfenger.dk\/wp-content\/uploads\/2019\/03\/hoodie-with-logo-2.jpg',
        'name': 'hoodie-with-logo-2.jpg',
        'alt': ''
      }],
      'attributes': [{
        'id': 1,
        'name': 'Color',
        'position': 0,
        'visible': true,
        'variation': false,
        'options': ['Blue', 'Green', 'Red']
      }, {'id': 0, 'name': 'Logo', 'position': 1, 'visible': true, 'variation': false, 'options': ['Yes', 'No']}],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 814, 'key': '_original_id', 'value': '45'}, {
        'id': 1646,
        'key': '_wpcom_is_markdown',
        'value': '1'
      }, {'id': 1649, 'key': '_wpas_done_all', 'value': '1'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/143'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }, {
      'id': 142,
      'name': 'V-Neck T-Shirt',
      'slug': 'v-neck-t-shirt',
      'permalink': 'https:\/\/www.victorfenger.dk\/product\/v-neck-t-shirt\/',
      'date_created': '2019-03-11T13:48:54',
      'date_created_gmt': '2019-03-11T13:48:54',
      'date_modified': '2019-03-11T13:49:03',
      'date_modified_gmt': '2019-03-11T13:49:03',
      'type': 'variable',
      'status': 'publish',
      'featured': true,
      'catalog_visibility': 'visible',
      'description': '<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.<\/p>\n',
      'short_description': '<p>This is a variable product.<\/p>\n',
      'sku': 'woo-vneck-tee',
      'price': '',
      'regular_price': '',
      'sale_price': '',
      'date_on_sale_from': null,
      'date_on_sale_from_gmt': null,
      'date_on_sale_to': null,
      'date_on_sale_to_gmt': null,
      'price_html': '',
      'on_sale': false,
      'purchasable': false,
      'total_sales': 0,
      'virtual': false,
      'downloadable': false,
      'downloads': [],
      'download_limit': 0,
      'download_expiry': 0,
      'external_url': '',
      'button_text': '',
      'tax_status': 'taxable',
      'tax_class': '',
      'manage_stock': false,
      'stock_quantity': null,
      'stock_status': 'outofstock',
      'backorders': 'no',
      'backorders_allowed': false,
      'backordered': false,
      'sold_individually': false,
      'weight': '',
      'dimensions': {'length': '', 'width': '', 'height': ''},
      'shipping_required': true,
      'shipping_taxable': true,
      'shipping_class': '',
      'shipping_class_id': 0,
      'reviews_allowed': true,
      'average_rating': '0.00',
      'rating_count': 0,
      'related_ids': [145],
      'upsell_ids': [],
      'cross_sell_ids': [],
      'parent_id': 0,
      'purchase_note': '',
      'categories': [{'id': 20, 'name': 'Tshirts', 'slug': 'tshirts'}],
      'tags': [],
      'images': [{
        'id': 167,
        'date_created': '2019-03-11T13:49:00',
        'date_created_gmt': '2019-03-11T13:49:00',
        'date_modified': '2019-03-11T13:49:00',
        'date_modified_gmt': '2019-03-11T13:49:00',
        'src': 'https:\/\/www.victorfenger.dk\/wp-content\/uploads\/2019\/03\/vneck-tee-2.jpg',
        'name': 'vneck-tee-2.jpg',
        'alt': ''
      }, {
        'id': 168,
        'date_created': '2019-03-11T13:49:01',
        'date_created_gmt': '2019-03-11T13:49:01',
        'date_modified': '2019-03-11T13:49:01',
        'date_modified_gmt': '2019-03-11T13:49:01',
        'src': 'https:\/\/www.victorfenger.dk\/wp-content\/uploads\/2019\/03\/vnech-tee-green-1.jpg',
        'name': 'vnech-tee-green-1.jpg',
        'alt': ''
      }, {
        'id': 169,
        'date_created': '2019-03-11T13:49:03',
        'date_created_gmt': '2019-03-11T13:49:03',
        'date_modified': '2019-03-11T13:49:03',
        'date_modified_gmt': '2019-03-11T13:49:03',
        'src': 'https:\/\/www.victorfenger.dk\/wp-content\/uploads\/2019\/03\/vnech-tee-blue-1.jpg',
        'name': 'vnech-tee-blue-1.jpg',
        'alt': ''
      }],
      'attributes': [{
        'id': 1,
        'name': 'Color',
        'position': 0,
        'visible': true,
        'variation': false,
        'options': ['Blue', 'Green', 'Red']
      }, {
        'id': 2,
        'name': 'Size',
        'position': 1,
        'visible': true,
        'variation': false,
        'options': ['Large', 'Medium', 'Small']
      }],
      'default_attributes': [],
      'variations': [],
      'grouped_products': [],
      'menu_order': 0,
      'meta_data': [{'id': 779, 'key': '_original_id', 'value': '44'}, {
        'id': 1629,
        'key': '_wpcom_is_markdown',
        'value': '1'
      }, {'id': 1632, 'key': '_wpas_done_all', 'value': '1'}],
      'jetpack_publicize_connections': [],
      '_links': {
        'self': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products\/142'}],
        'collection': [{'href': 'https:\/\/www.victorfenger.dk\/wp-json\/wc\/v3\/products'}]
      }
    }]
}